// export { default as Homepage } from './modules/home/homepage'
export { default as QAFormAudioSMP } from './modules/qaforms/qaforms-audio-smp/qaforms-audio-smp'
export { default as EditForms } from './modules/edit-forms/edit-forms'
// export { default as QAFormTAM } from './modules/qaforms/qaforms-tam/qaforms-tam'
export { default as GenerateNewReport } from './modules/generate-report/generate-report'
export { default as Operations } from './modules/analytics/operations/operations'
