export { default as QAFormAudioSMP } from './modules/qaforms/screens/audio-smp/AudioSMP'
export { default as QAFormAIAudioSMP } from './modules/qaforms/screens/audio-smp-ai/AIAudioSMP'
export { default as EditForms } from './modules/edit-forms/EditForms'
// export { default as QAFormTAMVideo } from './modules/qaforms/screens/tam-video/qaforms-tam'
export { default as GenerateNewReport } from './modules/generate-report/GenerateNewReport'
export { default as Operations } from './modules/analytics/operations/Operations'